---
- name: Install pre-deps
  apt: name=git
- name: Install scion-deploy ssh key
  copy: src=files/deploy.rsa dest=/home/scion/.ssh/id_rsa mode=0400
  remote_user: scion
- name: Make sure GOPATH exists in .profile
  lineinfile: dest=/home/scion/.profile line="export GOPATH=/home/scion/go"
  remote_user: scion
- name: Make sure PATH exists in .profile
  lineinfile: dest=/home/scion/.profile
              line="export PATH=\"/home/scion/.local/bin:/usr/lib/go-1.6/bin:$GOPATH/bin:$PATH\""
  remote_user: scion
- name: Make sure scion repo folder exists
  file: path={{repo_loc}} state=directory
  remote_user: scion
- name: Checkout SCION codebase
  git: repo=git@github.com:netsec-ethz/scion.git
       dest={{repo_loc}}
       version=master
       accept_hostkey=yes
  remote_user: scion
- name: Install all dependencies
  shell: APTARGS=-y ./deps.sh all chdir={{repo_loc}}
  remote_user: scion
- name: Get Go dependencies
  shell: bash --login -c "go get ./go/..." chdir={{repo_loc}}
  remote_user: scion
- name: Copy the basics of the gen directory
  copy: src={{local_gen}}/dispatcher  dest={{repo_loc}}/gens/{{ts}}/
  remote_user: scion
