---
- name: Setup ~root/.ssh/authorized_keys
  authorized_key: key="{{ lookup('file',toplevel+'/files/ansible.rsa.pub') }}" user=root
- name: Add scion user
  user: name=scion comment="SCION user" groups=sudo shell=/bin/bash
- name: Setup ~scion/.ssh/authorized_keys
  authorized_key: key="{{ lookup('file', toplevel+'/files/ansible.rsa.pub') }}" user=scion
