---
- hosts: switch_engines
  roles:
    - basic
  remote_user: ubuntu
  sudo: yes

- hosts: all
  roles:
    - basic
    - apt
    - ntp

- hosts: scion_nodes
  tasks:
  - set_fact:
      cfg_loc: ISD{{isd}}/AS{{as}}
      repo_loc: /home/scion/go/src/github.com/netsec-ethz/scion
      ts: "{{ lookup('pipe', [['stat', '--printf=%Y', inventory_file]]) }}"

- hosts: scion_nodes
  roles:
    - scion_node

- hosts: beacon_servers
  roles:
    - beacon_server

- hosts: path_servers
  roles:
    - path_server

- hosts: cert_servers
  roles:
    - cert_server

- hosts: edge_routers
  roles:
    - edge_router

- hosts: dns_servers
  roles:
    - dns_server

- hosts: sibra_servers
  roles:
    - sibra_server

- hosts: scion_nodes
  tasks:
    - name: Switch-over to the new gen folder
      file: src={{repo_loc}}/gens/{{ts}}
            dest={{repo_loc}}/gen
            state=link
  remote_user: scion
